#!/usr/bin/env python3
"""Prepare deterministic internal train/test traces from the public source set.

The source repository stores two-column traces as time in seconds and
throughput in Mbit/s. This script converts them to one Kbit/s value per second,
deduplicates identical traces, and creates source-stratified train/test splits.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
import re
import shutil
from collections import Counter
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_ROOT = PROJECT_ROOT / "data" / "raw" / "Real-world-bandwidth-traces"
DEFAULT_OUTPUT_ROOT = PROJECT_ROOT / "simulator" / "traces" / "real_world_split"

SOURCE_PATTERNS = {
    "cooked_3gp": ("cooked_3gp/*",),
    "fcc": ("fcc_ori/**/*.log",),
    "fcc_hsdpa": ("fcc_and_hsdpa/**/*",),
    "hsdpa": ("traces_3gp/*.log",),
    "oboe": ("traces_oboe/*.txt",),
    "puffer_211017": ("puffer_211017/**/*",),
    "puffer_220218": ("puffer_220218/**/*",),
}


def portable_path(path: Path) -> str:
    """Return a project-relative path for manifests when possible."""
    path = Path(path).resolve()
    try:
        return path.relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        return str(path)


def safe_float(value: str) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def read_mbps_points(path: Path) -> list[tuple[float, float]]:
    points = []
    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            timestamp = safe_float(parts[0])
            throughput_mbps = safe_float(parts[1])
            if timestamp is None or throughput_mbps is None or throughput_mbps <= 0.0:
                continue
            points.append((timestamp, throughput_mbps))
    return points


def resample_to_1hz_kbps(points: list[tuple[float, float]]) -> list[float]:
    if not points:
        return []

    points = sorted(points)
    base_time = points[0][0]
    relative = [(timestamp - base_time, value) for timestamp, value in points]
    duration = max(0, int(math.ceil(relative[-1][0])))
    buckets: list[list[float]] = [[] for _ in range(duration + 1)]
    for timestamp, value in relative:
        index = min(duration, max(0, int(math.floor(timestamp))))
        buckets[index].append(value)

    output = []
    last_value = relative[0][1]
    for bucket in buckets:
        if bucket:
            last_value = sum(bucket) / len(bucket)
        output.append(min(150_000.0, max(10.0, last_value * 1000.0)))
    return output


def trace_digest(values: list[float]) -> str:
    payload = "\n".join(f"{value:.2f}" for value in values)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def output_name(source: str, raw_rel_path: str, digest: str) -> str:
    slug = re.sub(r"[^A-Za-z0-9._-]+", "_", raw_rel_path).strip("._")
    return f"{source}__{slug[:120]}__{digest[:10]}.txt"


def write_trace(path: Path, values: list[float]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# 1 Hz Kbit/s trace generated by trace_tools/prepare_internal_traces.py\n"
        + "\n".join(f"{value:.2f}" for value in values)
        + "\n",
        encoding="utf-8",
    )


def prepare_output_root(path: Path, overwrite: bool) -> None:
    if path.exists() and any(path.iterdir()):
        if not overwrite:
            raise FileExistsError(f"{path} is not empty; pass --overwrite to replace it")
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def collect_source(
    source_root: Path,
    source_name: str,
    patterns: tuple[str, ...],
    min_seconds: int,
    max_files: int,
    seed: int,
    seen_digests: set[str],
) -> tuple[list[dict], Counter]:
    files = sorted(
        {
            path
            for pattern in patterns
            for path in source_root.glob(pattern)
            if path.is_file() and not path.name.startswith(".")
        }
    )
    candidates = []
    skipped = Counter()
    for path in files:
        values = resample_to_1hz_kbps(read_mbps_points(path))
        if len(values) < min_seconds:
            skipped["too_short_or_empty"] += 1
            continue
        digest = trace_digest(values)
        if digest in seen_digests:
            skipped["duplicate_content"] += 1
            continue
        seen_digests.add(digest)
        candidates.append(
            {
                "source": source_name,
                "raw_path": path,
                "raw_rel_path": path.relative_to(source_root).as_posix(),
                "seconds": len(values),
                "sha256": digest,
                "values": values,
            }
        )

    if max_files > 0 and len(candidates) > max_files:
        rng = random.Random(f"{seed}:{source_name}:limit")
        rng.shuffle(candidates)
        skipped["limited_by_max_files"] += len(candidates) - max_files
        candidates = candidates[:max_files]
    return candidates, skipped


def split_candidates(candidates: list[dict], test_ratio: float, seed: int, source_name: str):
    items = list(candidates)
    rng = random.Random(f"{seed}:{source_name}:split")
    rng.shuffle(items)
    test_count = int(round(len(items) * test_ratio))
    if len(items) > 1:
        test_count = min(len(items) - 1, max(1, test_count))
    else:
        test_count = 0
    return items[test_count:], items[:test_count]


def build_splits(
    source_root: Path,
    output_root: Path,
    seed: int,
    test_ratio: float,
    min_seconds: int,
    max_files_per_source: int,
    overwrite: bool,
) -> dict:
    if not source_root.is_dir():
        raise FileNotFoundError(
            f"Internal trace source not found: {source_root}. "
            "Clone confiwent/Real-world-bandwidth-traces into this directory."
        )
    if not 0.0 < test_ratio < 1.0:
        raise ValueError("test_ratio must be between 0 and 1")

    prepare_output_root(output_root, overwrite=overwrite)
    split_dirs = {name: output_root / name for name in ("train", "test")}
    for path in split_dirs.values():
        path.mkdir(parents=True, exist_ok=True)

    manifest = {
        "source": {
            "name": "confiwent/Real-world-bandwidth-traces",
            "url": "https://github.com/confiwent/Real-world-bandwidth-traces",
            "root": portable_path(source_root),
            "unit": "Mbit/s",
        },
        "output_root": portable_path(output_root),
        "output_unit": "Kbit/s",
        "seed": seed,
        "test_ratio": test_ratio,
        "min_seconds": min_seconds,
        "max_files_per_source": max_files_per_source,
        "summary": {},
        "skipped": [],
        "splits": {"train": [], "test": []},
    }

    seen_digests: set[str] = set()
    for source_name, patterns in SOURCE_PATTERNS.items():
        candidates, skipped = collect_source(
            source_root=source_root,
            source_name=source_name,
            patterns=patterns,
            min_seconds=min_seconds,
            max_files=max_files_per_source,
            seed=seed,
            seen_digests=seen_digests,
        )
        train_items, test_items = split_candidates(candidates, test_ratio, seed, source_name)
        manifest["summary"][source_name] = {
            "train": len(train_items),
            "test": len(test_items),
            "total": len(candidates),
        }
        for reason, count in sorted(skipped.items()):
            manifest["skipped"].append(
                {"source": source_name, "reason": reason, "count": count}
            )

        for split_name, items in (("train", train_items), ("test", test_items)):
            for item in items:
                target = split_dirs[split_name] / output_name(
                    source_name,
                    item["raw_rel_path"],
                    item["sha256"],
                )
                write_trace(target, item["values"])
                manifest["splits"][split_name].append(
                    {
                        "source": source_name,
                        "raw_rel_path": item["raw_rel_path"],
                        "output_name": target.name,
                        "seconds": item["seconds"],
                        "sha256": item["sha256"],
                        "output_rel_path": target.relative_to(output_root).as_posix(),
                    }
                )

    manifest_path = output_root / "manifest.json"
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    return manifest


def parse_args():
    parser = argparse.ArgumentParser(description="Prepare internal ABR trace train/test splits.")
    parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    parser.add_argument("--seed", type=int, default=20260506)
    parser.add_argument("--test-ratio", type=float, default=0.2)
    parser.add_argument("--min-seconds", type=int, default=60)
    parser.add_argument("--max-files-per-source", type=int, default=0)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest = build_splits(
        source_root=args.source_root,
        output_root=args.output_root,
        seed=args.seed,
        test_ratio=args.test_ratio,
        min_seconds=args.min_seconds,
        max_files_per_source=args.max_files_per_source,
        overwrite=args.overwrite,
    )
    for source_name, counts in manifest["summary"].items():
        print(
            f"{source_name}: total={counts['total']} "
            f"train={counts['train']} test={counts['test']}"
        )
    print(f"manifest: {Path(args.output_root) / 'manifest.json'}")


if __name__ == "__main__":
    main()
